{% set version = "0.2" %}

package:
  name: addrg
  version: {{ version }}

build:
  number: 0
  skip: False

source:
  fn: addrg-{{ version }}.tar.gz
  url: https://github.com/holtgrewe/addrg/archive/v0.2.tar.gz
  md5: '1da0562a4203259bdbd5a58b4da3fc2f'

requirements:
  build:
  - gcc  # [not osx]
  - llvm # [osx]
  - htslib >=1.0.0
  run:
  - libgcc # [not osx]
  - htslib >=1.0.0

about:
  home: https://github.com/holtgrewe/addrg
  license: MIT
  summary: Add read group to BAM files
test:
  commands:
  - '{ >&1 addrg || true; } | grep Usage'
